contact_plan:

  ######################
  # Contact parameters #
  ######################

  num_contacts: [3, 3, 0, 0]
  effcnt_rf:
    cnt0: [0.0, 1.0,   -1.82, 0.021,  0.155,    1.0, 0.0, 0.0, 0.0,           1.0]
    cnt1: [2.0, 4.5,   -1.55, 0.500,  0.30,    0.9689, 0.0, -0.2474, 0.0,    1.0]
    cnt2: [6.0, 9.9,   -1.02, 0.450,  0.80,    1.0, 0.0, 0.0, 0.0,           1.0]
  effcnt_lf:
    cnt0: [0.0, 2.5,   -2.21, -0.17,  0.155,    1.0, 0.0, 0.0, 0.0,           1.0]
    cnt1: [4.0, 6.5,   -1.5, -0.17,   0.55,    0.96891, 0.0,  0.2474, 0.0,   1.0]
    cnt2: [8.5, 9.9,   -0.9, -0.17,   0.8,    1.0, 0.0, 0.0, 0.0,           1.0]
  effcnt_rh:
  effcnt_lh:

planner_variables:

  #######################
  # Dynamics parameters #
  #######################

  heuristic: TrustRegion  # Types: TrustRegion, SoftConstraint, TimeOptimization #
  n_act_eefs: 2
  time_step: 0.1
  time_horizon: 9.5
  external_force: [0.00, 0.00, 0.00]
  com_displacement: [1.05, 0.20, 0.6]
  num_com_viapoints: 0
  com_viapoints:
    via0: [2.50,    0.500, 0.45,  0.00]

  #####################
  # Timing parameters #
  #####################

  max_time_iterations: 100
  max_time_residual_tolerance: 1e-3
  min_time_residual_improvement: 1e-5

  ############################
  # Configuration parameters #
  ############################

  gravity: 9.81
  robot_mass: 60.00
  friction_coeff: 1.0
  friction_cone: SocCone  # Types: LinearCone, SocCone #
  torque_range: [-200.0, 200.0]
  eff_offset_rf: [ 0.00,  0.00,  0.00]
  eff_offset_lf: [ 0.00,  0.00,  0.00]
  eff_offset_rh: [ 0.00,  -0.20,  0.48]
  eff_offset_lh: [0.00,  0.20,  0.48]
  cop_range_rf: [-0.08,  0.08, -0.03,  0.03]
  cop_range_lf: [-0.08,  0.08, -0.03,  0.03]
  cop_range_rh: [-0.03,  0.03, -0.03,  0.03]
  cop_range_lh: [-0.03,  0.03, -0.03,  0.03]
  max_eef_lengths: [0.82,  0.82,  0.60,  0.60]

  ####################
  # Dynamics weights #
  ####################

  w_trq_arm:       1.000
  w_trq_leg:       1.000
  w_com:           [ 10000,  10000,  10000]
  w_amom:          [ 0.500,  0.500,  0.500]
  w_lmom:          [ 0.001,  0.001,  0.001]
  w_amomd:         [ 0.400,  0.100,  0.100]
  w_lmomd:         [ 0.015,  0.015,  0.015]
  w_amom_final:    [ 10.00,  10.00,  10.00]
  w_lmom_final:    [ 10.00,  10.00,  10.00]
  w_com_via:       [ 0.000,  0.000,  0.000]
  w_frc_arm:       [ 0.001,  0.001,  0.001]
  w_frc_leg:       [ 0.001,  0.001,  0.001]
  w_dfrc_arm:      [ 0.000,  0.000,  0.000]
  w_dfrc_leg:      [ 0.000,  0.000,  0.000]
  w_amom_track:    [ 1.000,  1.000,  1.000]
  w_lmom_track:    [ 0.100,  0.100,  0.100]

  #######################
  # Storage information #
  #######################

  store_data: True

  ##################
  # Solver setting #
  ##################
  
  use_default_solver_setting: True
